export const CHANGE_DATES = 'TABLE/CHANGE_DATES'
export const SAVE_TABLE_DATA = 'TABLE/SAVE_TABLE_DATA'
export const SAVE_SALARY_DATA = 'SALARY/SAVE_SALARY_DATA'
export const SAVE_TOTAL_SUM = 'SALARY/SAVE_TOTAL_SUM'